// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJmNg4AEfpAhIvuzv-OZ0FEb_Td6lzhEc',
    appId: '1:409207619226:web:b78d73e14c27462a09e923',
    messagingSenderId: '409207619226',
    projectId: 'chatapp-1504d',
    authDomain: 'chatapp-1504d.firebaseapp.com',
    storageBucket: 'chatapp-1504d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwf_JzI0coF2VhWKPx7-w1uOBQ7RwjaFk',
    appId: '1:409207619226:android:fd9f35c0858d640409e923',
    messagingSenderId: '409207619226',
    projectId: 'chatapp-1504d',
    storageBucket: 'chatapp-1504d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQrgLRUVU81mevb2hdapJMzNLzfH78JOk',
    appId: '1:409207619226:ios:396eb6b42936ca8509e923',
    messagingSenderId: '409207619226',
    projectId: 'chatapp-1504d',
    storageBucket: 'chatapp-1504d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQrgLRUVU81mevb2hdapJMzNLzfH78JOk',
    appId: '1:409207619226:ios:396eb6b42936ca8509e923',
    messagingSenderId: '409207619226',
    projectId: 'chatapp-1504d',
    storageBucket: 'chatapp-1504d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJmNg4AEfpAhIvuzv-OZ0FEb_Td6lzhEc',
    appId: '1:409207619226:web:308265b58601e48d09e923',
    messagingSenderId: '409207619226',
    projectId: 'chatapp-1504d',
    authDomain: 'chatapp-1504d.firebaseapp.com',
    storageBucket: 'chatapp-1504d.firebasestorage.app',
  );
}
